### ISSUE TITLE
Microsoft Azure AD B2C Support

### ISSUE THREAD

**Issue by marratj** [ploxiln/oauth2_proxy#9]
Hi,

I just came across this maintained fork of oauth2_proxy.

A while ago, we had created a small fork ourselves to include support Microsoft Azure AD B2C authentication.

This is different from the normal AAD provider, in that it's OIDC, however with an added parameter called policy to control different user journeys through login.

So we basically just added the policy option to the OIDC provider but with that we also needed a fork of the go-oidc package from CoreOS so this can pass the policy option to the auth endpoint.

Ideally, we'd want to contribute to this repo here and get the AAD B2C support into here, too.

I'm open for any ideas on how we can make this possible going forword, ideally without relying on forking another external package.

We might use the forked go-oidc package as basis for an own AAD B2C provider and include it here.

Thoughts on this?

This is our fork: https://github.com/karrieretutor/oauth2_proxy

Best regards
Marcel

**Comment by ploxiln** [comment]
I'm open to it, it's just one more little command-line flag :) It comes down to whether it will actually have a user - if someone is really interested in using this fork, with just that one addition. (With no users, there's no real-world validation that it actually worked, because with `oauth2_proxy` it's _really really_ inconvenient to test that all the possible providers actually work with the real-world services. It depends on users noticing bugs with their provider setup.)

JoelSpeed mentioned the possibility of adding that parameter to the appropriate request without forking the go-oidc library, I'd be interested in looking into this possibility:

> Perhaps you can inject it like the HD param is done here? https://github.com/JoelSpeed/dex/blob/ccd954582b85162882656d0842e89af58f87d356/connector/google/google.go#L120

**Comment by ploxiln** [comment]
It looks like that particular "HD param" thing does not really apply to the go-oidc situation, but I wonder if it could be done by attaching a custom http client to the context with `ClientContext()`, which looks just for that `/.well-known/openid-configuration` url path and adds the param, before passing through to a plain/default http client.

**Comment by ploxiln** [comment]
reference for self: https://github.com/coreos/go-oidc/compare/v2...karrieretutor:v2

**Comment by marratj** [comment]
I will devote a bit more time into this beginning of 2019, as there definitely will be at least one user: our organization :) 

Instead of maintaining our own little fork for just that one feature, I'd still like to contribute in a more upstream way on this.

Just to let you know my thoughts on this :-)

**Comment by marratj** [comment]
The only issue with the OIDC provider in the way it's depending on the go-oidc package from CoreOS is that one can't set arbitrary URLs for the auth and token endpoints (which would allow to simply put the policy parameter into the URL).

Instead go-oidc has the hardcoded `"/.well-known/openid-configuration"` endpoint to gather the actual auth and token endpoints, which obviously doesn't include any parameters.

This is the only reason we can't use it directly with Azure AD B2C as it always needs this additional policy parameter.

**Comment by ploxiln** [comment]
Same, I'll look at this more after the holidays. It does seem like a small change, though go-oidc doesn't make it convenient ... I was thinking about trying to just copy-in and tweak that part of go-oidc (just a few functions and structs), while still using the rest of it from upstream.

**Comment by ploxiln** [comment]
(But yeah, if you can make this configurable in a way palatable to upstream, that would be very nice.)

**Comment by ploxiln** [comment]
closing in favor of https://github.com/pusher/oauth2_proxy/issues/27 and https://github.com/pusher/oauth2_proxy/pull/41
